// ── PDF EXPORT (jsPDF, loaded globally as window.jspdf) ─────────────────────────
import {showToast} from '../helpers.js';

export function exportPDF({res,recipeName,targetMl,t,lang,fmtEGP,flavors,pgBottlePrice,pgBottleSize,vgBottlePrice,vgBottleSize,nicBottlePrice,nicBottleSize,bottleCost,pgCost,vgCost,nicCost,steepDays,mixedOn}){
  if(!window.jspdf){showToast("jsPDF not loaded","error");return;}
  const{jsPDF}=window.jspdf;
  const doc=new jsPDF({orientation:"portrait",unit:"mm",format:"a4"});
  const isAr=lang==="ar";
  const primaryColor=[30,42,64];
  const accentColor=[96,165,250];

  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0,0,210,28,"F");
  doc.setTextColor(255,255,255);
  doc.setFontSize(16);doc.setFont("helvetica","bold");
  doc.text("EPP Calculator — E-Liquid Recipe",14,12);
  doc.setFontSize(10);doc.setFont("helvetica","normal");
  doc.text(`${recipeName||"Recipe"} | ${new Date().toLocaleDateString()}`,14,20);
  doc.text(`Volume: ${targetMl}ml`,160,20);

  // Composition summary
  doc.setTextColor(...primaryColor);
  doc.setFontSize(12);doc.setFont("helvetica","bold");
  doc.text("RECIPE DETAILS",14,36);
  doc.setLineWidth(0.5);doc.setDrawColor(...accentColor);
  doc.line(14,38,196,38);

  // Stats row
  doc.setFontSize(9);doc.setFont("helvetica","normal");
  const stats=[
    `PG: ${res.actualPg}%`,`VG: ${res.actualVg}%`,
    `Nicotine: ${res.actualNic}mg/ml`,`Cost: ${fmtEGP(res.totalCost,2)}`
  ];
  stats.forEach((s,i)=>{
    doc.setFillColor(240,244,248);doc.roundedRect(14+i*46,42,44,10,2,2,"F");
    doc.setTextColor(...primaryColor);doc.text(s,14+i*46+2,49);
  });

  // Ingredients table header
  let y=60;
  doc.setFillColor(...primaryColor);doc.rect(14,y,182,8,"F");
  doc.setTextColor(255,255,255);doc.setFontSize(9);doc.setFont("helvetica","bold");
  const cols=[["Ingredient",40],["ml",20],["g",18],["Drops",18],["% ",16],["Cost (EGP)",28],["Cost/ml",22]];
  let cx=16;
  cols.forEach(([lbl,w])=>{doc.text(lbl,cx,y+5.5);cx+=w;});

  // Rows
  const allItems=[res.nicotine,res.pg,res.vg,...(res.flavors||[]),res.water,res.alcohol].filter(x=>x&&x.ml>0);
  allItems.forEach((item,idx)=>{
    y+=8;
    if(idx%2===0){doc.setFillColor(248,250,252);}else{doc.setFillColor(255,255,255);}
    doc.rect(14,y,182,8,"F");
    doc.setTextColor(...primaryColor);doc.setFont("helvetica","normal");doc.setFontSize(9);
    cx=16;
    const vals=[
      item.name?.substring(0,20)||"",
      item.ml?.toFixed(2)||"0",
      item.g?.toFixed(2)||"0",
      item.drops?.toString()||"0",
      item.pct>0?`${item.pct}%`:"—",
      item.cost>0?fmtEGP(item.cost,2):"—",
      item.cost>0&&item.ml>0?fmtEGP(item.cost/item.ml,4):"—"
    ];
    vals.forEach((v,i)=>{doc.text(v,cx,y+5.5);cx+=cols[i][1];});
  });

  // Total row
  y+=8;
  doc.setFillColor(...primaryColor);doc.rect(14,y,182,9,"F");
  doc.setTextColor(255,255,255);doc.setFont("helvetica","bold");
  doc.text("TOTAL",16,y+6);
  doc.text(`${targetMl}ml`,56,y+6);
  doc.text(fmtEGP(res.totalCost,2),156,y+6);

  // Cost breakdown
  y+=16;
  if(y>250){doc.addPage();y=20;}
  doc.setTextColor(...primaryColor);doc.setFont("helvetica","bold");doc.setFontSize(11);
  doc.text("COST BREAKDOWN",14,y);
  doc.line(14,y+2,196,y+2);
  y+=8;
  const costItems=[
    ["PG",`${pgBottlePrice} EGP / ${pgBottleSize}ml`,fmtEGP(pgCost,4)+"/ml"],
    ["VG",`${vgBottlePrice} EGP / ${vgBottleSize}ml`,fmtEGP(vgCost,4)+"/ml"],
    ["Nicotine",`${nicBottlePrice} EGP / ${nicBottleSize}ml`,fmtEGP(nicCost,4)+"/ml"],
    ["Empty Bottle",fmtEGP(bottleCost,2),""],
  ];
  doc.setFont("helvetica","normal");doc.setFontSize(9);
  costItems.forEach(([name,price,pml])=>{
    doc.setFillColor(240,244,248);doc.rect(14,y,182,7,"F");
    doc.setTextColor(...primaryColor);
    doc.text(name,16,y+5);doc.text(price,80,y+5);doc.text(pml,150,y+5);
    y+=7;
  });

  // Steep info
  if(steepDays>0&&mixedOn){
    y+=6;
    const readyDate=new Date(new Date(mixedOn).getTime()+steepDays*86400000);
    doc.setFont("helvetica","bold");doc.setFontSize(10);
    doc.setTextColor(...primaryColor);
    doc.text("STEEPING",14,y);y+=5;
    doc.setFont("helvetica","normal");doc.setFontSize(9);
    doc.text(`Mixed: ${new Date(mixedOn).toLocaleDateString()}  |  Steep: ${steepDays} days  |  Ready: ${readyDate.toLocaleDateString()}`,14,y);
  }

  // Footer
  doc.setFontSize(8);doc.setTextColor(150,150,150);
  doc.text("Generated by EPP Calculator",14,287);
  doc.text(new Date().toLocaleDateString(),190,287,"right");

  doc.save(`${recipeName||"recipe"}-epp.pdf`);
  showToast(isAr?"تم حفظ PDF ✅":"PDF saved ✅","success");
}
